### ISSUE TITLE
python-google-places and new Google billing practices!

### ISSUE THREAD

**Issue by wbbroyles** [slimkrazy/python-google-places#119]
We've been using python-google-places for several months with great results to pull basic place data -- counts of things, mostly, like how many banks in a given area?  I don't really care about names, photos, ratings, website, etc.   Works great!

In July, Google introduced new billing based on which fields of a Place query result you access.  The basic data -- name, address, etc. -- are free, but "contact data" like opening hours have a cost, and "atmosphere data" like ratings have a cost.

In my Python code, I'm not accessing any "contact data" or "atmosphere data", or even any "basic data" only counting the number of places returned.  What I'm wondering is if, under the covers to be helpful, python-google-places is grabbing *all* the information about a Place -- contact, atmosphere, and basic -- and returning it in the structure just in case I want it after the call to the nearby search.  That would indeed be very helpful of python-google-places under the old billing paradigm where only the number of searches counted towards billing, but if python-google-places is indeed grabbing every piece of Place data to help me, it's going to kill me under the new pricing algorithm.

Can anyone confirm for me whether python-google-places is grabbing all the Place data (contact, atmosphere, etc.) even if all I do is call for the nearby search and count the number of entries in the returned list?  It's the only explanation for why I have identical numbers on my billing statement for the number of calls to Nearby Search, Basic Data, Contact Data, and Atmosphere Data.

Thanks in advance,
Brad

**Comment by wbbroyles** [comment]
Closed per explanation from Google billing.

**Comment by scottwilson312** [comment]
@wbbroyles did you get an answer to this question?

**Comment by wbbroyles** [comment]
Yes, I think I figured it out on my own and deleted the issue.  The charges were documented and I just missed it.

Brad Broyles
Principal Software Engineer
MetLife Enterprise Application Development
919-694-9130
william.b.broyles@metlife.com
Visit the Accelerating Analytics Knowledge Share Site<https://my.metlife.com/sites/AnalyticsCommunity/SitePages/Home.aspx> │ Contact the Advanced Analytics Team<https://my.metlife.com/sites/AnalyticsCommunity/SitePages/GADS%20Advanced%20Analytics%20Service%20Offerings%20-%20Pilot.aspx>
