### ISSUE TITLE
Google autocomplete api issue (Response structure changed)

### ISSUE THREAD

**Issue by kapilmatani** [slimkrazy/python-google-places#126]
In the response structure of autocomplete API, **'id'**  field is missing in some results.

Example:
'https://maps.googleapis.com/maps/api/place/autocomplete/json?input=bangalore&language=&components=country%3AIN&radius=3200&location=None%2CNone&types=%28regions%29&sensor=false&key='

In above api result having description - "Bangalore South, Karnataka, India" does not contain **'id'** as a field.

This library code is breaking in __init__.py line no. 641
class Prediction(object):
    """
    Represents a prediction from the results of a Google Places Autocomplete API query.
    """
    def __init__(self, query_instance, prediction):
        self._query_instance = query_instance
        self._description = prediction['description']
        **self._id = prediction['id']**
        self._matched_substrings = prediction['matched_substrings']
        self._place_id = prediction['place_id']
        self._reference = prediction['reference']
        self._terms = prediction['terms']
        self._types = prediction.get('types',[])
        if prediction.get('_description') is None:
            self._place = None
        else:
            self._place = prediction

**Comment by MrUpsidown** [comment]
https://developers.google.com/places/web-service/autocomplete#place_autocomplete_results
id is not part of the returned list of fields

**Comment by evgenybf** [comment]
I haven't checked the issue for a long time, but it seems on July 10th, 2020 the error got back.

**Comment by davidmarquis** [comment]
@evgenybf I'm indeed experiencing the exact same issue today. 

I'll probably migrate to https://github.com/googlemaps/google-maps-services-python instead, which seems to have a Places API client for Python.

**Comment by 3dw1np** [comment]
When the patch will be merge?
