### ISSUE TITLE
next_page_token in nearbysearch

### ISSUE THREAD

**Issue by deepakagrawal** [slimkrazy/python-google-places#19]
I noticed that there is no option for getting query result from next page. Because google place api gives at max total 60 results in 3 pages. It will be good to add the next page option. 
I don't how can I edit the repository to add that, so if can anyone please do that or guide me how to do that?

**Comment by dieguico** [comment]
I strongly support the inclusion of next_page_token. :)

**Comment by slimkrazy** [comment]
I need time to check over some old pull requests. I'm sure that it's been done already - I just need to get it tested and merge it in. 

Time: I wish I had more of it. I'll try to pencil in a couple of hours for me to look at it over the weekend.

**Comment by dieguico** [comment]
:+1:

**Comment by matias-piin** [comment]
:+1:

**Comment by mceoin** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by bprazen** [comment]
This addition would be great. Is it still in the works?

**Comment by mohammedayub44** [comment]
Has this been already been merged or not integrated into the module, b'coz I did not see any parameter in the function arguments ? If not, it would be a great addition.

**Comment by slimkrazy** [comment]
Released in version 1.4.0.
