### ISSUE TITLE
Remove deprecated properties: reference & id

### ISSUE THREAD

**Issue by commadelimited** [slimkrazy/python-google-places#30]
At what point would you like me to begin work on removing reference and id? When you do expect you'll merge `development` into `master`? Or would you like me to work on removing them before you merge? Do you want to submit two different versions to PyPi, or bump a single cohesive change containing autocomplete and removal of deprecated props?

**Comment by ldiqual** [comment]
@commadelimited Any update on this? I'd like to move forward with using `placeid` only.
