### ISSUE TITLE
add custom __repr__ to Place and GooglePlacesSearchResult

### ISSUE THREAD

**Issue by scottcode** [slimkrazy/python-google-places#43]
I just came across this project. Thanks to all of you who've been putting it together. As I start using it, I'll see if there are ways I can help out. 

One thing I noticed is that the `Place` and `GooglePlacesSearchResult` classes don't override `object`'s __repr__. I know it's a minor aesthetic thing, but it would be nice to have. 

For `Place` it could look something like `<Place name=[obj.name]>` (using the name attribute). What do you think?

**Comment by slimkrazy** [comment]
Hey scottcode - Please feel free to submit a pull request to the development branch for this. It's a useful feature for sure.
