### ISSUE TITLE
Can't figure out geocide_location

### ISSUE THREAD

**Issue by tandrews1** [slimkrazy/python-google-places#51]
When I try to run 
`lat_long = google_places.geocode_location("Brighton, MA", sensor=False)`

google_places is an instance of GooglePlaces (from the example). 

I get the following:Traceback (most recent call last):
  File "./google_places.py", line 10, in <module>
    lat_long = google_places.geocode_location("Brighton, MA", sensor=False)
AttributeError: 'GooglePlaces' object has no attribute 'geocode_location'

Could someone point me in the right direction? I notice the reference uses a 'googleplaces' object but I cannot figure out how to locate or instantiate it.
`googleplaces.geocode_location(location, sensor=False)`

Thanks,
Taylor

**Comment by slimkrazy** [comment]
Sounds like you did not import the geocode_location function.

from googleplaces import GooglePlaces, geocode_location

YOUR_API_KEY = 'AIzaSyCDgUgYXtQR-Iflasa0P4M5v'
google_places = GooglePlaces(YOUR_API_KEY)

lat_long = geocode_location("Brighton, MA", sensor=False)
print(lat_long)
