### ISSUE TITLE
A text search makes 10 API requests

### ISSUE THREAD

**Issue by minhle1291** [slimkrazy/python-google-places#63]
Hi,

Thanks for setting this up... incredibly helpful! I noticed that a simple .text_search was costing me 10 API requests each time. Is anyone else experiencing this issue?

Sample:
def getCounty(cityState):
    API_KEY = 'blahblahabcdefg'
    google_places = GooglePlaces(API_KEY)
    query_result = google_places.text_search("What county is " + cityState + " in")
    for place in query_result.places:
        return place.name

Yes, yes, I know I can accomplish the same task with Geocoding! Thanks! :)

**Comment by jarmani** [comment]
Hi,

That's how google account api call on text search.

> The Google Places search services share the same usage limits. However, the Text Search service is subject to a 10-times multiplier. That is, each Text Search request that you make will count as 10 requests against your quota.

https://developers.google.com/places/web-service/search#TextSearchRequests
