### ISSUE TITLE
20 result only

### ISSUE THREAD

**Issue by nepthys** [slimkrazy/python-google-places#73]
The script returns 20 result only. 
How to get all results?

**Comment by wroberts** [comment]
+1

**Comment by nepthys** [comment]
wroberts,
I was mistaken, that's why I didn't get any answer.
The code returns 20 results (all results for the page 1) but you can use the value "query_result.next_page_key" obtain 60 results (results for the pages 2 and 3).

After your firect query, just check if the next page exists. 
If so, you can execute another query:

if query_result.next_page_key:
        time.sleep(2)#wait to avoid error
        query_result = google_places.nearby_search(next_page_token=query_result.next_page_key )

**Comment by karthikapp** [comment]
Hi the above code doesn't seem to work. 
I get the following error 
AttributeError: 'GooglePlacesSearchResult' object has no attribute 'next_page_key'

**Comment by slimkrazy** [comment]
This feature has been released in version 1.4.0. Please check the README for usage.
