### ISSUE TITLE
Get rid of mutable default arguments

### ISSUE THREAD

**Issue by nickwilliams-eventbrite** [slimkrazy/python-google-places#82]
This library currently suffers from the use of mutable default arguments, described [here](http://docs.python-guide.org/en/latest/writing/gotchas/). This was mentioned in issue #59 (in [this comment](https://github.com/slimkrazy/python-google-places/issues/59#issuecomment-255414722)). These should be corrected.

**Comment by slimkrazy** [comment]
Released in version 1.4.0. 

Thanks for the fix!
