### ISSUE TITLE
geocode_location not an attribute?

### ISSUE THREAD

**Issue by robertlmyers** [slimkrazy/python-google-places#88]
Hello, I am trying to use the geocoding feature by passing it an address.  It says the below doesn't exist. Am I using this wrong?

googleplaces.geocode_location(location, sensor=False)
  Converts a human-readable location to a Dict containing the keys: lat, lng.
  Raises googleplaces.GooglePlacesError if the geocoder fails to find the
  specified location.

My work around is using the places nearby, populating the latitude and longitude from places using a for loop, but my terrible coding is not letting this work, so I figured I'd ask if the geocode_location is supposed to still exist somewhere? I am using 1.3.

**Comment by slimkrazy** [comment]
Hey @robertlmyers,

Doesn't this simple code work for you?

```
from googleplaces import geocode_location
print geocode_location('Buckingham Palace')
```

**Comment by robertlmyers** [comment]
Sorry, I didn't realize I needed to import geocode_location. Still learning. I thought it was a part of the Google places import from the readme.  Thanks for the response!
