### ISSUE TITLE
is repo DEAD ?

### ISSUE THREAD

**Issue by keradus** [slimkrazy/python-google-places#89]
no reply for bugfixes older than 3 months, eg #76

**Comment by slimkrazy** [comment]
Repo is not dead, I'm just _very_ busy.

This project is quite old, and honestly I'd like to refactor the whole thing (potentially making some backward incompatible changes) before trying to resolve some of the issues.

I'll apply some of the simple PR's, run some smoke tests and push to PyPi by tomorrow evening.

**Comment by matkoniecz** [comment]
It seems to be dead again.

**Comment by matkoniecz** [comment]
Unfortunately it seems to be dead again. But thanks for publishing it, what is available is still quite useful :)
