### ISSUE TITLE
Getting inconsistent list of POIs when changing radius

### ISSUE THREAD

**Issue by commapp** [slimkrazy/python-google-places#90]
Hi! Thanks for writing this. It is very useful!

The problem I am facing is that given a lat/lng, I want to get the POIs nearby based on a radius. Here is an example:

mydict = {}
mydict['lat'] = 38.72961
mydict['lng'] = -75.54783
# You may prefer to use the text_search API, instead.
query_result = google_places.nearby_search(
        lat_lng=mydict,
        types=[types.TYPE_POINT_OF_INTEREST],
        radius=3800
        )

If I modify the radius to be 7000, there are POIs that disappear when it should be the opposite. It should display more POIs, if available, right?

List with radius of 3800(Ignore the "Yes" and "No"):
No Subway
No Punkin Chunkin
No Royal Farms
No Cardtronics ATM
No ATM (Royal Farms)
No Sonic Drive-In
No Cigars For Less
No Mary Kay Cosmetics
No Scott's Furniture Inc
Yes Horney Industrial Electronics
No Nothing Better LLC
No kristys kakes
No Bridgeville Rifle and Pistol Club
No LR Construction
No Sussex Tree Inc
No Circle C Outfit
No Bay To Beach Builders
No Dance Moves & Manners
Yes DEP PIPES USA LLC
No Fellowship Health Resources

List with radius of 7000(Ignore the "No"):
No Subway
No Royal Farms
No Punkin Chunkin
No Cardtronics ATM
No Walgreens
No ATM (Royal Farms)
No Warren Truss Co Inc
No Dollar General
No Sonic Drive-In
No Cigars For Less
No Tractor Supply Co.
No Bridgeville Emporium
No Ryan Homes
No Fireside Hearth & Home
No Scott's Furniture Inc
No Phillis Wheatley Elementary School
No Jeff's Taproom & Grille
No US Post Office
No Barton's Mini Storage
No Four Paws Animal Hospital

**Comment by commapp** [comment]
I tried using text_search but getting the below error:

Traceback (most recent call last):
  File "/Users/SDN/PycharmProjects/cell_site_v2/google_places.py", line 15, in <module>
    query_result = google_places.text_search(types=[types.TYPE_POINT_OF_INTEREST],radius=3800)
TypeError: text_search() takes at least 2 arguments (3 given)

**Comment by commapp** [comment]
I was able to find the issue with text_search. I was missing the query parameter. I now get the same output with 20 POIs. How do I iterate over the next? I check within the raw result and there is a token for the next page, but I dont know how to use it.

**Comment by slimkrazy** [comment]
Hey @commapp  - Please use the code from the development branch. It has support for the next page token. The README in that branch also has an example on how to use it.

Let me know how you get on. I want to have it merged to master this week.

**Comment by commapp** [comment]
Cool! Let me try it and will keep you posted.

**Comment by commapp** [comment]
Here are my results:

I ran it in debug mode once or twice and it worked. Now it is giving the below error. I place the url in the browser and it returns the data. 

mydict = {}
pois = []
mydict['lat'] = 38.72961
mydict['lng'] = -75.54783
query_result = google_places.nearby_search(lat_lng=mydict,radius=7000,types=[types.TYPE_POINT_OF_INTEREST])

while query_result.has_next_page_token:
    for place in query_result.places:
        pois.append(place.name)
    time.sleep(2)
    query_result = google_places.nearby_search(pagetoken=query_result.next_page_token)



Traceback (most recent call last):
  File "/Users/SDN/PycharmProjects/cell_site_v2/google_places.py", line 30, in <module>
    query_result = google_places.nearby_search(pagetoken=query_result.next_page_token)
  File "/Users/SDN/anaconda/lib/python2.7/site-packages/googleplaces/__init__.py", line 303, in nearby_search
    _validate_response(url, places_response)
  File "/Users/SDN/anaconda/lib/python2.7/site-packages/googleplaces/__init__.py", line 173, in _validate_response
    raise GooglePlacesError(error_detail)
googleplaces.GooglePlacesError: Request to URL https://maps.googleapis.com/maps/api/place/nearbysearch/json?language=en&pagetoken=CpQCBgEAAMgLjs3J4ZXMeYXYsB31b6AUnZqDFArUNbFcTmhgXxbiiMyUjgATy3DFII-jyr2aedxeMKGuOOojTwU0HCPUMI8mbDgvZCCOPDEXmDUCH9fQXjdiJN1hFABhFIdiV1nhjJ2rq8AwkWNVbRVM7nzvOKPTL1CbReQ3_97KmLzV1ae_zPMLeBok2jL7FZm1Xx-bw6mLyXk7H2o93h-QTsEkh7NIDUL6cyRnai0_ycwUryeN3l9ToEnKm5sCG893S7sH6fIlli5AIzpHwZnccnYd7cCsspObQ7pErdoSdV8NCuAFRdGtSuDreOV_wqlRaYxFfR2DLHWd8brHfxWlY9PpqSNF4q_5cL_HlJluXx97MHqvEhCfbtTIIU4gqHSSaLkbE8hMGhRs3RXtsnYhdiTosug3bvLLHAHQvA&radius=3200&location=44.9334927%2C7.5407494&key=REMOVED_FOR_SECURITY&sensor=false failed with response code: INVALID_REQUEST

**Comment by commapp** [comment]
I ran it again and I am not getting the error. No changes to the code.

I am able now to get the next pages, but I still see discrepancy between points. 

if I use radius of 3800, I get POIs that I dont get using 7000. See below.

in 3800 radius but not in 7000.
Horney Industrial Electronics
DEP PIPES USA LLC
Huey
Perry Poultry
Robert Carl Trucking Inc

**# 3800:**
Subway
Punkin Chunkin
Royal Farms
Cardtronics ATM
ATM (Royal Farms)
Sonic Drive-In
Cigars For Less
Mary Kay Cosmetics
Scott's Furniture Inc
Horney Industrial Electronics
Nothing Better LLC
kristys kakes
Bridgeville Rifle and Pistol Club
LR Construction
Sussex Tree Inc
Circle C Outfit
Bay To Beach Builders
Dance Moves & Manners
DEP PIPES USA LLC
Fellowship Health Resources
Food Lion
Hopkins Construction Inc
Pizza King
The Pavilion at TS Smith & Sons
Photography by Lloydlee Heite
Cox's RV Repair
Western Union
pet emporium
Coinstar
Cricke Custom Skimboards
FAMILY DOLLAR
Seaford Concrete Products LLC
Delaware State Police
Gene's Auto Sales
Redbox
Walkers Mill Mobile Home Park
Central Park Mini Storage
BP
McDonald's
Insight Homes, Linkside Village
Bridgeville Tires
Ray's Electrical Services
R Dennis Construction Llc
One Plus One International
First State Community Action Agency
Wall Papering By Deb
Huey
Jmw Trucking
JR's Painting
Myer's Grocery
SR18/404 @ Walkers Mill Rd
SR 18/404 Opp Walkers Mill Rd
De Rt 18/404 East at Chaplins Chapel Rd
De Rt 18/404 East at Coverdale Rd
Perry Poultry
Robert Carl Trucking Inc
The Frozen Farmer
Passwaters Agricultural Services
Wheatley Farms Inc
K & L Trucking


**# 7000:**
Subway
Royal Farms
Punkin Chunkin
Cardtronics ATM
Walgreens
ATM (Royal Farms)
Warren Truss Co Inc
Dollar General
Sonic Drive-In
Cigars For Less
Tractor Supply Co.
Bridgeville Emporium
Ryan Homes
Fireside Hearth & Home
Scott's Furniture Inc
Phillis Wheatley Elementary School
Jeff's Taproom & Grille
US Post Office
Barton's Mini Storage
Four Paws Animal Hospital
That Granite Place
Heritage Shores
Counter Intelligence - Granite Countertops in Delaware (DE)
Goodwill of Delaware and Delaware County
Insight Homes
Barton's Grand Rental Station
Telamon Corporation
Miller Metal Fabrication
Weller's Utility Trailers
Hopkins Automotive
Dolby & Associates Inc
Seaford Church of Christ
Crossroad Community Church
Mary Kay Cosmetics
Utility Eastern Shore Trailer
chambers motors inc
Lou's Salvage, Inc.
PNC Bank
Delaware State Police
Parsell Funeral Homes & Crematorium
Roberts Oxygen
O.A. Newton
First State Fabrication
Bridgeville Public Library
A C Schultes of Delaware Inc
Delaware Department of Health
Peninsula Chemical LLC
Central Park Mini Storage
Bridgeville State Services Center
Woodbridge School District
Food Lion
Pizza King
Helena Chemical Co
Gene's Auto Sales
Weller's Utility Trailers
Tony's Pizza & Pasta
Delmarva Carbonic
Plant Retrievers Wholesale Nursery, LLC
Passwater's Restaurant
Heritage Shores Golf Shop

**Comment by commapp** [comment]
I figured that is something to do with Google APIs and not with your code... I am using radar_search instead to get more POIs but I am facing another error when using getPlace... I will open a new issue and close this one.
