### ISSUE TITLE
Next page token for nearby_search fails with lat_lon required.

### ISSUE THREAD

**Issue by commapp** [slimkrazy/python-google-places#92]
Hey slimkrazy,

I noticed that nearby_search fails when going to the next page asking for lat_lon. I looked at the code and added on my side that if page_toke is None, then run 

lat_lng_str = self._generate_lat_lng_string(lat_lng, location)
self.request_params = {'location' : lat_lng_str}

That fixed the issue. But in fact a cleaner way would be to add all the needed parameters when pagetoken is None and when a pagetoken is added, just add the pagetoken and the key to the url.

Hope this helps.

Luis

**Comment by pablolp99** [comment]
Hey Luis, i've had the same error, i'm trying to fix it myself, but at least i'm not the only one.

Pablo

**Comment by slimkrazy** [comment]
Guys,

I'm travelling at the moment, so I'll take a look  at this when I get back
in three days.

On Tue, 14 Feb 2017 3:38 am pablolp99, <notifications@github.com> wrote:

Hey Luis, i've had the same error, i'm trying to fix it myself, but at
least i'm not the only one.

Pablo

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/slimkrazy/python-google-places/issues/92#issuecomment-279590802>,
or mute the thread

**Comment by pablolp99** [comment]
Ok, is not a big deal for me right now. Thanks by the attention

**Comment by hangtwenty** [comment]
I've been getting this issue too. I found a few threads about this API, that said you have to wait for the next-page token to be "ready." [Here's one.](http://stackoverflow.com/questions/24445478/unable-to-access-google-places-api-after-passing-next-page-token-in-nodejs/24445937#24445937) (Found other threads but didn't save them.) In that thread, someone suggests they do a sleep for 2 seconds. In another thread, I saw someone say it could take 5 seconds for them.

This constraint in the API is probably not a big deal for a web-application with an end user (they are probably spending time on page 1 before requesting page 2), but it is a bit of a bummer for other use cases.

**Comment by hangtwenty** [comment]
Here is a snippet I'm using to deal with this constraint. I don't think this is generic enough to merge to master in this repository but maybe it'll give other folks some ideas.

```python
import googleplaces
from funcy import retry

class GooglePlacesService(object):
    """ Wrapper around Google Places Web API.

    current implementation uses python-google-places library.
    """

    NEARBY_SEARCH = "nearby_search"
    TEXT_SEARCH = "text_search"
    RADAR_SEARCH = "radar_search"

    def __init__(self, api_key):
        self.google_places = GooglePlaces(api_key=api_key)

    def search(self, search_type, *args, **kwargs):
        if search_type == self.NEARBY_SEARCH:
            return self.google_places.nearby_search(*args, **kwargs)
        elif search_type == self.TEXT_SEARCH:
            return self.google_places.text_search(*args, **kwargs)
        elif search_type == self.RADAR_SEARCH:
            return self.google_places.radar_search(*args, **kwargs)
        else:
            raise TypeError("search type not supported (yet) by wrapper around python-google-places")

    @retry(tries=5, errors=googleplaces.GooglePlacesError, timeout=lambda attempt: 1 + attempt * 0.5)
    def search_with_delay_and_retry(self, search_type, *args, **kwargs):
        """ Search with an initial sleep, plus retrying. Useful for those pesky "next-page-token" delays.

        See:
        - https://github.com/slimkrazy/python-google-places/issues/92
        - http://stackoverflow.com/questions/24445478/
        """
        return self.search(search_type=search_type, *args, **kwargs)
```

That `@retry` decorator is from `funcy`, which I use in almost every project. If you didn't want the dependency, the implementation of such a decorator would not be difficult (source is small).  http://funcy.readthedocs.io/en/stable/flow.html But `funcy` is pretty great, I recommend it 😬

**Comment by slimkrazy** [comment]
Hey,

Are you sure this is an issue with the code, or an issue with making calls back up to Google prior to the next page data being ready?  Are you able to execute the following code without issues?

```
from time import sleep

from googleplaces import GooglePlaces, types, GooglePlacesError


MAX_FETCH = 200
google_places = GooglePlaces('YOUR_TOKEN_HERE')

query_result = google_places.nearby_search(
        location='London, England', keyword='Fish and Chips',
        radius=20000, types=[types.TYPE_FOOD])

fetched = 0
while fetched < MAX_FETCH:
  for place in query_result.places:
    print '[%i] %s' %(fetched, place.name)
    fetched = fetched + 1
  if query_result.has_next_page_token:
    sleep(3)
    print '========================================='
    print '[NPT: %s]' % query_result.next_page_token
    print '========================================='
    query_result = google_places.nearby_search(
        pagetoken=query_result.next_page_token)
```

**Comment by commapp** [comment]
Hi @slimkrazy!

Sorry I have been disconnected on this for a WHILE. I have not tried this approach yet as I was pulled to another effort, but I am hoping the effort will come back again in the next few months. I will keep you posted. For now, I will close this issue.

**Comment by anadaf** [comment]
I had the same issue and resolved the issue by downgrading python-google-places from 1.4.1 to 1.4.0
