### ISSUE TITLE
Question about the google.places.text_search

### ISSUE THREAD

**Issue by felixha95** [slimkrazy/python-google-places#95]
Hi,

I was using your library to query the google places api and I found out that I get the error OVER_QUERY_LIMIT. I've read that this is due to the limit google puts to the user queries to its API (2,500 free requests per day or 50 requests per second) That's why I'd like to know if there is any way of limiting the number of results from the query, so I don't exceed that limit.

Thanks,

Felix.

**Comment by slimkrazy** [comment]
Hey Felix,

This would be beyond the remit of this library. Different users could have different limits, depending on what they've (or not) paid for, or even where else they may be using their quota.

It would be best managed by your own application logic and probably a database.
